name: Homey App Validate

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/checkout@v3
        with:
          node-version: '20' # Homey anv√§nder nyare Node-versioner

      - name: Install Homey CLI
        run: npm install -g homey

      - name: Validate App
        run: homey app validate
        